contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #variantsimulator channel"
    url: https://nfcore.slack.com/channels/variantsimulator
    about: Discussion about the nf-core/variantsimulator pipeline
